### ISSUE TITLE
Can't reproduce results in the paper

### ISSUE THREAD

**Issue by weilonghu** [JinheonBaek/RGCN#1]
Hi,
Thanks for your excellent job! This is the only repo I can find that is implemented in torch_geometric. But I can't reproduce results using your code. Can you show me your results and configurations.
Thanks.

**Comment by JinheonBaek** [comment]
Thanks for your interest, and really sorry for replying very late.

In the previous version, there was a very subtle bug in the data perturbation part which is used for ranking metric.
The bug is now fixed, and I hope that the code works fine.

If you find any additional issues, feel free to let me know!

**Comment by ShellingFord221** [comment]
Hi, I have tried new codes on FB15k-237, the result is as follows:
![image](https://user-images.githubusercontent.com/40685673/136680518-6fc293e0-2781-4555-86c6-9d2011cbdd88.png)
It seems that reproduced performance is quite low. Is there any possible reason? Thanks!

**Comment by zhijiejia** [comment]
> Hi, I have tried new codes on FB15k-237, the result is as follows: ![image](https://user-images.githubusercontent.com/40685673/136680518-6fc293e0-2781-4555-86c6-9d2011cbdd88.png) It seems that reproduced performance is quite low. Is there any possible reason? Thanks!

May the hidden dim should be more? I see the RGCN in pytorch_geometric, the dim of embedding is 500 rather than 100.

The link of RGCN in pytorch_geometric : 
https://github.com/pyg-team/pytorch_geometric/blob/master/examples/rgcn_link_pred.py
