### ISSUE TITLE
best_mrr_model.pth

### ISSUE THREAD

**Issue by zqyJason** [JinheonBaek/RGCN#11]
__where can I find the 'best_mrr_model.pth'?

**Comment by eric2213** [comment]
Hi! 
I got the same problem, 

FileNotFoundError: [Errno 2] No such file or directory: 'best_mrr_model.pth'

May I ask how did you solve it?

**Comment by linxiang1911** [comment]
你们最后是怎么解决的，我也遇到这不到这个路径

**Comment by eric2213** [comment]
> 你们最后是怎么解决的，我也遇到这不到这个路径

I didn’t fix it, use DGL instead.

**Comment by JinheonBaek** [comment]
Hi all, to obtain this file: best_mrr_model.pth, you must do train first and then save the checkpoint. 
See this line: https://github.com/JinheonBaek/RGCN/blob/master/main.py#L84
