### ISSUE TITLE
Which version do u use ? I have some troubles in torch_scatter

### ISSUE THREAD

**Issue by DengYaosheng** [JinheonBaek/RGCN#2]
It is a great jobs and I'm very appreciate about it.
But when i trying to : pip install torch_scatter the terminal returns a stack red error seems that my cuda version not fitted with it
So could u please tell me about the version u use ?
Thanks a lot~

**Comment by JinheonBaek** [comment]
Hello,
thanks for your interest.

I'm using pytorch 1.4.0 version, and torch_scatter 2.0.4 version.
Also, the code was tested on cuda 10.1 environment.
