### ISSUE TITLE
Why did it appear killed when training the model

### ISSUE THREAD

**Issue by ReadyTeresa** [JinheonBaek/RGCN#3]

**Comment by JinheonBaek** [comment]
Thank for your interest.

Can you specify the detail of errors for training?
Then, I will check it.

Sincerely,
Jinheon Baek

**Comment by ReadyTeresa** [comment]
> Thank for your interest.
> 
> Can you specify the detail of errors for training?
> Then, I will check it.
> 
> Sincerely,
> Jinheon Baek


No errors are printed out, but the server will be killed when executing the valid function at line 80

**Comment by JinheonBaek** [comment]
I will first check the error, and then let you know.
Thank you for sharing the issue.

**Comment by sunke-github** [comment]
It caused by out of memory. When the model begins evaluation, It needs about 64g memory.

**Comment by JinheonBaek** [comment]
It seems, as @sunke-github pointed out, the error is caused by out-of-memory, not the memory for GPU but the memory for CPU.
