### ISSUE TITLE
RGCN model conv1 is applied two times.

### ISSUE THREAD

**Issue by moritzblum** [JinheonBaek/RGCN#5]
In the RGCN model, conv1 is applied twice in succession. Is that intended?

```
x = self.conv1(x, edge_index, edge_type, edge_norm)        
x = F.relu(self.conv1(x, edge_index, edge_type, edge_norm))
```

**Comment by JinheonBaek** [comment]
This is not intended, and thank you for pointing out this. I actually did not notice this error.
This error will be fixed soon.

Thanks,
Jinheon Baek
