### ISSUE TITLE
Why building test graph requires train_triplets?

### ISSUE THREAD

**Issue by zhaohan-xi** [JinheonBaek/RGCN#8]
Hi Dear Author, in this [line](https://github.com/JinheonBaek/RGCN/blob/818bf70b00d5cd178a7496a748e4f18da3bcde82/main.py#L48), building the test_graph has train triplets as input, isn't it test triplets actually?

**Comment by JinheonBaek** [comment]
Thank you for your question.

This is a nice question, and we use the test_graph (all train triplets) to get embeddings of entities on the given graph, which are further used to test the model on the test triplets. In other words, the test triplet's entity embedding is obtained from the RGCN outputs of the test_graph (train_triplets).
